spring:
  application:
    name: USER-SERVICE
  boot:
    admin:
      client:
        url: http://localhost:9091/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost





